### ISSUE TITLE
Create local Action that takes care of LTA on the fly deployment.

### ISSUE THREAD

**Issue by danielsiegl** [LieberLieber/LemonTree.Automation.Workflows#116]
The stuff prototyped in:
"LTA Auto Deploy - ConsistencyCheck.yml "

Should be encapsulated in a local Action to make it faster and easier to switch all workflows to public runners.

**Comment by danielsiegl** [comment]
https://betterprogramming.pub/4-steps-to-creating-a-custom-github-action-d67c4cf0445a
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

**Comment by danielsiegl** [comment]
First Try the plumbing works
https://github.com/LieberLieber/LemonTree.Automation.Workflows/runs/6174878747?check_suite_focus=true

**Comment by danielsiegl** [comment]
BEst Guide to do it:

**Comment by danielsiegl** [comment]
@FlorianBeerRB we have a public action ==> "Isolation has it's benefits"

https://github.com/LieberLieber/setup-LemonTree.Automation/

```
      - name: GetLTA
        uses: LieberLieber/setup-LemonTree.Automation@v0.1
        id: GetLTA
        with:
          License: ${{secrets.LTALICENSE}}
```
